### ISSUE TITLE
Figure Export

### ISSUE THREAD

**Issue by straussmaximilian** [OmicEra/OmicLearn#12]
- Using the latest version
- Alzheimer Dataset

I noted that some of the image exports seem to be buggy.

Confusion Matrix:
Clicking on the Plotly-Camera icon to download the png will lead to a confusion matrix with broken colors.
![Unknown-12](https://user-images.githubusercontent.com/16521288/109190905-e3c36d00-7795-11eb-9f34-3f87a5ec7b63.png)

Clicking on the PDF export will always export the sum of all splits and not individual CM. This could potentially be hard to fix, but in case, we could just mention the limitations.

In general, the aspect ratio seems to be different when exporting a pdf when comparing the png version.
<img width="955" alt="Screen Shot 2021-02-25 at 18 21 31" src="https://user-images.githubusercontent.com/16521288/109191281-4b79b800-7796-11eb-9089-ad0832173cdb.png">

**Comment by furkanmtorun** [comment]
Hey Max,

I have just checked the issue again.

1. **For me, Plotly Camera button was working well (using Chrome v88) and it was able to capture each individual CM:**
![newplot (1)](https://user-images.githubusercontent.com/49681382/109613121-c7cb1d00-7b41-11eb-90b1-de4fc7bfcf50.png)
![newplot (2)](https://user-images.githubusercontent.com/49681382/109613124-c863b380-7b41-11eb-8a0a-e1df0c7188d8.png)

2. **Also, I have reverted back the bg color of Plotly tool from blackish to white to make it the same like others:**

From:
![image](https://user-images.githubusercontent.com/49681382/109613652-81c28900-7b42-11eb-8978-2398897eacab.png)

To:
![image](https://user-images.githubusercontent.com/49681382/109616116-d3204780-7b45-11eb-885b-142f55c06ed5.png)

3. **Finally, I have also spent a great time fixing that exported PDF image ratios for all images 👍** 

Old:
![image](https://user-images.githubusercontent.com/49681382/109615867-80df2680-7b45-11eb-9930-e8dde40e0934.png)

Current:
![image](https://user-images.githubusercontent.com/49681382/109615917-905e6f80-7b45-11eb-9af6-01ebca7fa182.png)


> CM specific PDF-SVF download option remains still an issue since it is most probably hard to fix it.

---

Besides them, I also corrected the capitalization of the words and titles.

See commits:
- https://github.com/OmicEra/OmicLearn/commit/4674d973b2c3f746d4529bb2332fd190cb06d311
- https://github.com/OmicEra/OmicLearn/commit/4b11b64b35a039b795983369fd23bb2413319c4c
---

Best,
Furkan

**Comment by straussmaximilian** [comment]
Hi,
I can confirm that for Chrome the Camera Button works well, so it seems to be a Safari Problem.
PDF export now works much better. Great.
For PDF it still does not update the individual split but I think the overview is the most important anyhow.

**Comment by furkanmtorun** [comment]
Hey again,

Thanks for reply!
Yeah, again I checked the Opera and M. Edge that are Chromium-based web-browsers, work well. So, it might be Safari specific.
Also, agree on the PDF exporting part.

Hence, I am closing the issue then!

Best
